### ISSUE TITLE
Update 6_2_user_and_group_settings.rb to mock empty array.

### ISSUE THREAD

**Issue by jcarapet** [dev-sec/cis-dil-benchmark#1]
#Ran into this while trying an `inspec check` against this profile on my workstation 

**Steps to Reproduce**
inspec version: 1.19.1

1. clone project to workstation
2. run `inspec check`

**Expected Output**
Successful run 

**Actual Output**
```
jcarap0915mac:171107 jcarap$ inspec check cis-dil-benchmark/
command(sestatus).exist?` is not suported on your OS: 
command(sestatus).exist?` is not suported on your OS: 
command(sestatus).exist?` is not suported on your OS: 
command(sestatus).exist?` is not suported on your OS: 
command(sestatus).exist?` is not suported on your OS: 
command(sestatus).exist?` is not suported on your OS: 
command(ntpd).exist?` is not suported on your OS: 
command(chronyd).exist?` is not suported on your OS: 
command(rsyslogd).exist?` is not suported on your OS: 
command(rsyslogd).exist?` is not suported on your OS: 
command(rsyslogd).exist?` is not suported on your OS: 
command(rsyslogd).exist?` is not suported on your OS: 
command(rsyslogd).exist?` is not suported on your OS: 
command(syslog-ng).exist?` is not suported on your OS: 
command(syslog-ng).exist?` is not suported on your OS: 
command(syslog-ng).exist?` is not suported on your OS: 
command(syslog-ng).exist?` is not suported on your OS: 
command(syslog-ng).exist?` is not suported on your OS: 
cis-dil-benchmark/controls/6_2_user_and_group_settings.rb:114:in `block in load_with_context': undefined method `split' for nil:NilClass (NoMethodError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/rule.rb:51:in `instance_eval'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/rule.rb:51:in `initialize'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/control_eval_context.rb:71:in `new'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/control_eval_context.rb:71:in `block (2 levels) in create'
	from cis-dil-benchmark/controls/6_2_user_and_group_settings.rb:106:in `load_with_context'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/profile_context.rb:146:in `instance_eval'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/profile_context.rb:146:in `load_with_context'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/profile_context.rb:130:in `load_control_file'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/profile.rb:144:in `block in collect_tests'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/profile.rb:141:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/profile.rb:141:in `collect_tests'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/profile.rb:426:in `load_checks_params'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/profile.rb:419:in `load_params'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/profile.rb:134:in `params'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/profile.rb:299:in `controls_count'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/profile.rb:270:in `check'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/lib/inspec/cli.rb:69:in `check'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.19.1/bin/inspec:12:in `<top (required)>'
	from /opt/chefdk/bin/inspec:57:in `load'
	from /opt/chefdk/bin/inspec:57:in `<main>'
```

**steps to fix**
Adam Leff from the inspec team was kind enough to provide a working solution already. 

https://github.com/dev-sec/cis-dil-benchmark/blob/master/controls/6_2_user_and_group_settings.rb#L114

`
#### OLD CODE ##### 
root_path = os_env('PATH').content.split(':')

#### REPLACEMENT CODE ####
root_path = os_env('PATH').content.split(':')
root_path = root_path.nil? ? [] : root_path.split(':')
`

**Comment by vorsprung** [comment]
the pull request I've left also addresses this problem

https://github.com/dev-sec/cis-dil-benchmark/pull/2/files
