### ISSUE TITLE
Getting undefined method `split' for nil:NilClass (NoMethodError) on MacOS

### ISSUE THREAD

**Issue by Constantin07** [dev-sec/cis-dil-benchmark#3]
Hello,

I'm getting a strange error on MacOS when trying to bundle this profile for uploading to Compliance server.

```
$ inspec version
1.50.1
```

```
$ inspec archive ./cis-dil-benchmark
I, [2018-01-24T16:53:28.034487 #33478]  INFO -- : Checking profile in ./cis-dil-benchmark
I, [2018-01-24T16:53:28.034682 #33478]  INFO -- : Metadata OK.
./cis-dil-benchmark/controls/6_2_user_and_group_settings.rb:114:in `block in load_with_context': undefined method `split' for nil:NilClass (NoMethodError)
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/lib/inspec/rule.rb:50:in `instance_eval'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/lib/inspec/rule.rb:50:in `initialize'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/lib/inspec/control_eval_context.rb:75:in `new'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/lib/inspec/control_eval_context.rb:75:in `block (2 levels) in create'
	from ./cis-dil-benchmark/controls/6_2_user_and_group_settings.rb:106:in `load_with_context'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/lib/inspec/profile_context.rb:156:in `instance_eval'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/lib/inspec/profile_context.rb:156:in `load_with_context'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/lib/inspec/profile_context.rb:140:in `load_control_file'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/lib/inspec/profile.rb:167:in `block in collect_tests'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/lib/inspec/profile.rb:164:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/lib/inspec/profile.rb:164:in `collect_tests'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/lib/inspec/profile.rb:470:in `load_checks_params'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/lib/inspec/profile.rb:463:in `load_params'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/lib/inspec/profile.rb:157:in `params'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/lib/inspec/profile.rb:323:in `controls_count'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/lib/inspec/profile.rb:294:in `check'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/lib/inspec/cli.rb:139:in `archive'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.50.1/bin/inspec:12:in `<top (required)>'
	from /usr/local/bin/inspec:23:in `load'
	from /usr/local/bin/inspec:23:in `<main>'
```

**Comment by vorsprung** [comment]
this is exactly the same fault as described in issue#1 https://github.com/dev-sec/cis-dil-benchmark/issues/1
apply my patch or apply the fix that @jcarapet describes

**Comment by Constantin07** [comment]
@vorsprung Thanks
